name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - name: Run unit tests
      run: python -m unittest discover -s tests
    
    - name: Test main draw execution
      run: python -m src.champions_league_draw
    
    - name: Test statistics module
      run: python -m src.statistics
    
    - name: Test export module
      run: python -m src.export_json

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t ucl-draw:${{ github.sha }} .
    
    - name: Test Docker image
      run: docker run ucl-draw:${{ github.sha }}

  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Check syntax
      run: python -m py_compile src/*.py tests/*.py
    
    - name: Check for common issues
      run: |
        python -c "import ast, pathlib; [ast.parse(f.read_text()) for f in pathlib.Path('src').glob('*.py')]; [ast.parse(f.read_text()) for f in pathlib.Path('tests').glob('*.py')]"
        echo "All Python files have valid syntax"

